version: '3.8' # Specifies the Docker Compose file format version

services:
  agentic_ai:
    build:
      context: .
    image: agentic_ai:latest
    container_name: agentic_ai
    ports:
      - "5055:5055"
    env_file:
      - .env
    restart: unless-stopped
